"""create_tpmpk_tables

Revision ID: 68014c9be4a5
Revises: 
Create Date: 2026-04-25 18:04:56.954930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68014c9be4a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tpmpk_schedule_template',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('is_working_default', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot_minutes BETWEEN 10 AND 240 AND slot_minutes % 5 = 0', name='tpmpk_schedule_template_slot_minutes_chk'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='tpmpk_schedule_template_weekday_chk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekday')
    )
    op.create_table('tpmpk_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('totp_secret', sa.LargeBinary(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'operator')", name='tpmpk_user_role_chk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tpmpk_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tpmpk_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tpmpk_working_day',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('slot_minutes BETWEEN 10 AND 240 AND slot_minutes % 5 = 0', name='tpmpk_working_day_slot_minutes_chk'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['tpmpk_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('tpmpk_appointment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('working_day_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('child_full_name', sa.LargeBinary(), nullable=False),
    sa.Column('child_age', sa.Integer(), nullable=False),
    sa.Column('parent_phone', sa.LargeBinary(), nullable=False),
    sa.Column('is_repeat', sa.Boolean(), nullable=True),
    sa.Column('needs_psychiatrist', sa.Boolean(), nullable=True),
    sa.Column('consent_pd', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('consent_special', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source IN ('site', 'phone')", name='tpmpk_appointment_source_chk'),
    sa.CheckConstraint("status IN ('new', 'confirmed', 'cancelled', 'done')", name='tpmpk_appointment_status_chk'),
    sa.CheckConstraint('child_age BETWEEN 0 AND 18', name='tpmpk_appointment_child_age_chk'),
    sa.CheckConstraint('consent_pd IS TRUE', name='tpmpk_appointment_consent_pd_chk'),
    sa.CheckConstraint('consent_special IS TRUE', name='tpmpk_appointment_consent_special_chk'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['tpmpk_user.id'], ),
    sa.ForeignKeyConstraint(['working_day_id'], ['tpmpk_working_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tpmpk_appointment_slot_uniq', 'tpmpk_appointment', ['working_day_id', 'start_time'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    op.create_table('tpmpk_slot_lock',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('working_day_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('locked_by_session', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['working_day_id'], ['tpmpk_working_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tpmpk_slot_lock_uniq', 'tpmpk_slot_lock', ['working_day_id', 'start_time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tpmpk_slot_lock_uniq', table_name='tpmpk_slot_lock')
    op.drop_table('tpmpk_slot_lock')
    op.drop_index('tpmpk_appointment_slot_uniq', table_name='tpmpk_appointment', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_table('tpmpk_appointment')
    op.drop_table('tpmpk_working_day')
    op.drop_table('tpmpk_audit_log')
    op.drop_table('tpmpk_user')
    op.drop_table('tpmpk_schedule_template')
    # ### end Alembic commands ###
